# Set sleep timeout to 15min (15min*60000=ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Enable mouse
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# Bluetooth tweaks
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Max number of bt devices + 1
CONFIG_BT_MAX_CONN=4 
# This must be the same as the value above
CONFIG_BT_MAX_PAIRED=4 

# Enables battery level monitoring for both halves (requires app to fully work)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y